# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-WrwETmsIdr8a0-11b7kt9JTLIG2LUa
"""

!pip install streamlit

import streamlit as st

st.write('Hello, *World!* :sunglasses:')